# Generated by Django 2.2.6 on 2019-10-31 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('launch', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(help_text='Enter a brief description of the game', max_length=1000)),
                ('appid', models.CharField(help_text='13', max_length=13, verbose_name='AppID')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular game across whole library', primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=200)),
                ('reservation', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Announced'), ('o', 'Out of stock'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Game availability', max_length=1)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Game')),
            ],
            options={
                'ordering': ['reservation'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='catalogo.Platform'),
        ),
    ]
