# Generated by Django 2.2.6 on 2019-10-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='appid',
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=0, help_text='Enter the price of the game in clp$', verbose_name='Price'),
        ),
    ]
