# Generated by Django 2.2.6 on 2019-11-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20191031_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
