# Generated by Django 2.2.6 on 2019-11-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Image',
            new_name='image',
        ),
    ]
