# Generated by Django 2.2.6 on 2019-11-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20191103_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='NonEpicGames/catalogo/static/img'),
        ),
    ]
