# Generated by Django 2.2.6 on 2019-11-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20191103_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='requirements',
            field=models.TextField(default='No Requirements found', help_text='Enter the systems requirements', max_length=1000),
        ),
    ]
