# Generated by Django 2.2.6 on 2019-11-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20191113_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
