# Generated by Django 2.2.7 on 2019-11-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_delete_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='xxxxx@xxxx.com', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='No ingresado', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='No ingresado', max_length=30),
        ),
    ]
